spring:
  application:
    name: demo-app

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    username: ${DB_USER:appuser}
    password: ${DB_PASS:apppass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 60000

  cache:
    type: redis

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

#spring:
#  application:
#    name: demo-app
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:prod}
#
#server:
#  port: ${SERVER_PORT:8080}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "health,info"
#  endpoint:
#    health:
#      probes:
#        enabled: true
#spring:
#  application:
#    name: demo-app
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:prod}
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#
#server:
#  port: ${SERVER_PORT:8080}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info   # ✅ expose các endpoint cần
#  endpoint:
#    health:
#      show-details: always     # ✅ hiện chi tiết tình trạng health




